# -*- coding: utf-8 -*-
"""Лабораторная работа №1,Мырша Дмитрий

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UOlf3Lxd3yoPB2r78F-5qhqsy86FVDrE
"""

print ("Hello world")

a = 5
b = 2
c = a + b
print (c)

print ("Hello world")

a=7.5
b=7.5
S=a/2*(b**2-a**2/2)
print (S)

print ("Hello world")

a=int(input())

b=int(input())

c=int(input())

x=(a**2+b**2-c**3)/2
print (x)

print ("Hello world")

a=5
b = int(input())

c=a*b
print(c)

print ("Hello world")

a = int(input())

b = int(input())

c=(a+b)**2
print (c)

print ("Hello world")

a=15
b=10

c = int(input())

m=(a+b)/c
print (m)

print ("Hello world")

a = int(input())

b = int(input())

c=(a+b)**2
print (c)

print ("Hello world")

a=int(input())

b=int(input())

c=int(input())

p=a+b+c
print (p)

s=(p/2*(p/2-a)*(p/2-b)*(p/2-c))**0.5
print (s)

print ("Hello world")

a=int(input())

b=int(input())

c=((a**3+14)/5)*b
print (c)

print ("Hello world")

a=int(input())

b=a**2
print(b)

n=int(input())

x=b/n
print (x)

print ("Hello world")

c=a//b
print (c)

m=int(input())
n=int(input())
h=m*n
print (h)

j=int(input())
s=int(input())
n=j%s
print (n)

print ("Hello world")

sec = int(input())
h = sec//3600
m = (sec-h*3600)//60
s = sec%60
print (h,'час', m,'мин', s,'сек')

print ("Hello world")

n=input()
n1 = n
n2 = n*2
n3 = n*3
print(int(n1) + int(n2) + int(n3))