# -*- coding: utf-8 -*-
"""Лабораторная работа №3,Мырша Дмитрий

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xe-4zH926Q-fqxurP4ZzvsIgtszxeXi0
"""

#nomer 1
mes = int(input("Вводи номерочек месяца: "))
if(mes<=0 or mes > 12):
      print("Нумерация же месяцов идёт от 1 до 12")
else:
      if(mes == 1):
        print("Январь")
      elif(mes == 2):
        print("Февраль")
      elif(mes == 3):
        print("Март")
      elif(mes == 4):
        print("Апрель")
      elif(mes == 5):
        print("Май")
      elif(mes == 6):
        print("Июнь")
      elif(mes == 7):
        print("Июль")
      elif(mes == 8):
        print("Август")
      elif(mes == 9):
        print("Сентябрь")
      elif(mes == 10):
        print("Октябрь")
      elif(mes == 11):
        print("Ноябрь")
      elif(mes == 12):
        print("Декабрь")

#nomer 2
n = int(input("Введи число, и я сотворю магию: "))

if not float(n)%2:
  print("Чётное")
else:
  print("Нечётное")

#nomer 3
n = int(input("Введите уровень вашего успех: "))

if (float(n) >= 40):
  print("Stonks")
else:
  print("Not stonks")

#nomer 4
year = int(input("Введите номер года: "))
def is_year_leap(arg):
  return arg%400==0 or arg%4==0 and arg%100!=0
if(is_year_leap(year)):
  print(is_year_leap(year), "\tГод - високосный")
else:
  print(is_year_leap(year), "\tГод - невисокосный")

#nomer 5
num = int(input("Введите число: "))
def is_prime(n):
  s=2
  while n%s!=0:
    s+=1
  return s==n

print(is_prime(num))
if(is_prime(num)):
  print("Число простое")
else:
  print("Число составное")

#nomer 6
import math
num1 = float(input("Введите значение 1: "))
num2 = float(input("Введите значение 2: "))
n1 = (-138/2)**1.3
n2 = math.fabs((-69/(28**5.1))*4)
aogr1 = n1.real
bogr1 = n1.imag
realn1 = -1*(aogr1**2 + bogr1**2)**0.5
print("До проверки для обмена значений: ", "\n  num1 = ", num1, "\n  num2 = ", num2)
if(num1 > 3.6*num2) or (num2 >= realn1 and num2 <= n2):
  num1, num2 = num2, num1
print("После проверки для обмена значений: ", "\n  num1 = ", num1, "\n  num2 = ", num2)

#nomer 7
arrN = []
n1 = float(input("Введите первое число: "))
arrN.append(n1)
n2 = float(input("Введите второе число: "))
arrN.append(n2) 
n3 = float(input("Введите третье число: "))
arrN.append(n3) 
n4 = float(input("Введите четвёртое число: "))
arrN.append(n4) 
n5 = float(input("Введите пятое число: "))
arrN.append(n5)
print(*arrN)
kcet = 0
kotr = 0
kprom = 0
knecet = 0
uniq = 1
mnozarrN = set(arrN)
if len(arrN) != len(mnozarrN):
  uniq = 0
for j in range(0, len(arrN)-1):
  # print(j)
  if(arrN[j]%2 == 0):
    kcet += 1
  if arrN[j]%2 != 0:
    knecet += 1
  if(arrN[j] < 0):
    kotr += 1
  if(arrN[j]>=-256 and arrN[j]<=1024):
    kprom += 1
if uniq:
  print("Все числа уникальные.")
else:
  print("Есть одинаковые числа.")
print("Количество чётных чисел:", kcet, '\nКоличество нечётные числа:', knecet, '\nКоличество отрицальных чисел:', kotr, '\nКоличество чисел в промежутке [-256 ; 1024]:', kprom)

#Повышенной сложности
import math
a = float(input("Введите число a: "))
b = float(input("Введите число b: "))
c = float(input("Введите число c: "))

bl1 = a**2 + b**3
bl2 = c + 3
if bl2 == 0:
  res = math.inf
else:
  res = (bl1/bl2)/4
if res%2 == 0:
  if res == math.inf:
    print("Ответ стремится к неконечности. \tИ чётное, и нечётное")
  else:
    print("Ответ:", res, '\tЧётное')
else:
  if res == math.inf:
    print("Ответ стремится к неконечности. \tИ чётное, и нечётное")
  else:
    print("Ответ:", res, '\tНечётное')